backend:
  name: git-gateway
  branch: main  # Specify the branch you want to work with (e.g., 'main' or 'master')

media_folder: "static/images/uploads"  # The folder where images will be stored
public_folder: "/images/uploads"      # The public URL path to the images

collections:
  - name: "posts"  # The name of the collection for posts
    label: "Blog Posts"
    folder: "content/posts"  # The folder where posts will be stored
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
