backend:
  name: git-gateway
  branch: main  # Your repository's default branch

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}/{{month}}/{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }

admin:
  url: "https://yidecrwanda.netlify.app/admin/"
