name: Generate Blog Index

on:
  push:
    paths:
      - 'static/content/blog/**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate blog index
        run: node generate-blog-index.js

      - name: Commit and push updated index
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add static/content/blog/index.json
          git commit -m "Update blog index [skip ci]" || echo "No changes to commit"
          git push
